// Package main demonstrates YubiKey OTP authentication.
//
// This example shows how to:
// - Configure the YubiKey authenticator
// - Validate YubiKey OTPs
// - Use the YubiCloud validation service
// - Handle errors properly
//
// Usage:
//   go run basic_example.go
package main

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/jhahn/go-auth/pkg/yubikey"
)

func main() {
	fmt.Println("==> YubiKey OTP Authentication Example")
	fmt.Println()

	// Configure YubiKey authenticator
	// To use YubiCloud (Yubico's validation service):
	// 1. Get API credentials: https://upgrade.yubico.com/getapikey/
	// 2. Enter your email and YubiKey OTP
	// 3. You'll receive a Client ID and API Key
	cfg := yubikey.Config{
		ClientID: "12345",                        // Your YubiCloud Client ID
		APIKey:   "your-base64-encoded-api-key=", // Your YubiCloud API Key
	}

	// Create authenticator with YubiCloud validator
	// Note: This example uses YubiCloud. For self-hosted validation servers,
	// you would implement a custom OTPValidator.
	auth, err := yubikey.NewAuthenticator(cfg, nil)
	if err != nil {
		log.Fatalf("Failed to create YubiKey authenticator: %v", err)
	}

	// Create context with timeout
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// Example YubiKey OTP
	// A real OTP is 44 characters long and generated by pressing the YubiKey button
	// Format: [device_id][token]
	// Example: ccccccbcgujhingjrdejhgfnuetrgigvejhhgbkugded
	otp := "ccccccbcgujhingjrdejhgfnuetrgigvejhhgbkugded"

	fmt.Println("Validating YubiKey OTP...")
	fmt.Printf("OTP: %s\n", otp)
	fmt.Println()

	// Perform authentication
	// The authenticator sends the OTP to the validation service
	// which verifies:
	//   1. The OTP is valid
	//   2. The OTP hasn't been used before (replay protection)
	//   3. The signature is correct
	err = auth.Authenticate(ctx, otp)
	if err != nil {
		if err == yubikey.ErrInvalidOTP {
			log.Printf("Invalid OTP - rejected by validation service")
		} else {
			log.Printf("Authentication failed: %v", err)
		}
		fmt.Println()
		fmt.Println("Note: This example requires:")
		fmt.Println("  1. YubiCloud API credentials (or self-hosted validator)")
		fmt.Println("  2. A physical YubiKey to generate OTPs")
		fmt.Println("  3. Network connectivity to api.yubico.com")
		fmt.Println()
		fmt.Println("To get started:")
		fmt.Println("  1. Visit: https://upgrade.yubico.com/getapikey/")
		fmt.Println("  2. Enter your email and generate an OTP with your YubiKey")
		fmt.Println("  3. Save your Client ID and API Key")
		fmt.Println("  4. Update the cfg.ClientID and cfg.APIKey in this example")
		fmt.Println("  5. Press your YubiKey to generate a fresh OTP and run again")
		return
	}

	fmt.Println("✓ Authentication successful!")
	fmt.Println()
	fmt.Println("The YubiKey OTP has been validated by YubiCloud.")
	fmt.Println()
	fmt.Println("YubiKey OTP features:")
	fmt.Println("  - One-time passwords (cannot be reused)")
	fmt.Println("  - Strong replay protection")
	fmt.Println("  - No driver installation required")
	fmt.Println("  - Works as a USB keyboard")
	fmt.Println("  - Suitable for two-factor authentication")
	fmt.Println()
	fmt.Println("For self-hosted validation:")
	fmt.Println("  - Deploy YubiKey Validation Server")
	fmt.Println("  - Implement custom OTPValidator interface")
	fmt.Println("  - Pass to NewAuthenticator() instead of nil")
}
